import { useState, useEffect, useRef } from 'react';
import { motion } from 'framer-motion';
import { Play, Pause, RotateCcw, Download, Loader2 } from 'lucide-react';
import { RenderTask } from '../types';

interface VisualizationCanvasProps {
  renderTask: RenderTask | null;
  onVideoLoaded?: (video: HTMLVideoElement) => void;
}

export function VisualizationCanvas({ renderTask, onVideoLoaded }: VisualizationCanvasProps) {
  const [videoKey, setVideoKey] = useState(0);
  const videoRef = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    if (renderTask?.status === 'completed' && renderTask.videoUrl) {
      setVideoKey(prev => prev + 1);
    }
  }, [renderTask?.status, renderTask?.videoUrl]);

  const handleVideoLoaded = () => {
    if (videoRef.current && onVideoLoaded) {
      onVideoLoaded(videoRef.current);
    }
  };

  const getVideoUrl = () => {
    if (renderTask?.videoUrl) {
      return renderTask.videoUrl;
    }
    return 'https://www.w3schools.com/html/mov_bbb.mp4';
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5, delay: 0.1 }}
      className="flex-1"
    >
      <div className="h-full flex flex-col gap-4">
        <div className="bg-slate-900/50 backdrop-blur-xl border border-slate-800 rounded-2xl p-4 flex-1 flex flex-col">
          <div className="mb-4 flex items-center justify-between">
            <div>
              <h2 className="text-xl font-semibold text-white mb-1">Visualization Canvas</h2>
              <p className="text-sm text-slate-400">Generated by Manim Engine</p>
            </div>
            {renderTask && (
              <div className="flex items-center gap-2">
                <div className={`px-3 py-1.5 rounded-full text-xs font-medium ${
                  renderTask.status === 'completed'
                    ? 'bg-green-500/20 text-green-300 border border-green-500/50'
                    : renderTask.status === 'processing'
                    ? 'bg-blue-500/20 text-blue-300 border border-blue-500/50'
                    : renderTask.status === 'failed'
                    ? 'bg-red-500/20 text-red-300 border border-red-500/50'
                    : 'bg-slate-500/20 text-slate-300 border border-slate-500/50'
                }`}>
                  {renderTask.status.toUpperCase()}
                </div>
              </div>
            )}
          </div>

          <div className="flex-1 bg-slate-950 rounded-xl border border-slate-800 overflow-hidden flex items-center justify-center relative">
            {!renderTask ? (
              <div className="text-center p-12">
                <Play className="w-20 h-20 text-slate-700 mx-auto mb-4" />
                <p className="text-slate-500 text-lg">Start a visualization to see it here</p>
              </div>
            ) : renderTask.status === 'processing' || renderTask.status === 'queued' ? (
              <div className="text-center p-12">
                <Loader2 className="w-16 h-16 text-blue-400 mx-auto mb-6 animate-spin" />
                <p className="text-blue-300 text-lg mb-2">Rendering Animation...</p>
                <div className="w-64 h-2 bg-slate-800 rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${renderTask.progress}%` }}
                    transition={{ duration: 0.5 }}
                    className="h-full bg-gradient-to-r from-blue-500 to-cyan-500"
                  />
                </div>
                <p className="text-slate-400 text-sm mt-2">{Math.round(renderTask.progress)}% complete</p>
              </div>
            ) : renderTask.status === 'completed' ? (
              <div className="w-full h-full">
                <video
                  key={videoKey}
                  ref={videoRef}
                  controls
                  className="w-full h-full object-contain"
                  src={getVideoUrl()}
                  autoPlay={false}
                  onLoadedMetadata={handleVideoLoaded}
                >
                  Your browser does not support the video tag.
                </video>
              </div>
            ) : (
              <div className="text-center p-12">
                <div className="w-16 h-16 bg-red-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                  <RotateCcw className="w-8 h-8 text-red-400" />
                </div>
                <p className="text-red-300 text-lg">Rendering failed</p>
                <p className="text-slate-400 text-sm mt-2">Please try again</p>
              </div>
            )}
          </div>

          {renderTask?.status === 'completed' && (
            <div className="mt-4 flex gap-3">
              <button className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors">
                <Play className="w-4 h-4" />
                Play
              </button>
              <button className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors">
                <Pause className="w-4 h-4" />
                Pause
              </button>
              <button className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors">
                <RotateCcw className="w-4 h-4" />
                Restart
              </button>
              <button className="flex items-center gap-2 px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors ml-auto">
                <Download className="w-4 h-4" />
                Download
              </button>
            </div>
          )}
        </div>

        {renderTask && (
          <motion.div
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="bg-slate-900/50 backdrop-blur-xl border border-slate-800 rounded-xl p-4"
          >
            <h3 className="text-sm font-semibold text-white mb-3">Render Status</h3>
            <div className="grid grid-cols-3 gap-4 text-center">
              <div>
                <p className="text-xs text-slate-400 mb-1">Task ID</p>
                <p className="text-sm font-mono text-slate-300">{renderTask.id.substring(0, 12)}...</p>
              </div>
              <div>
                <p className="text-xs text-slate-400 mb-1">Progress</p>
                <p className="text-sm font-semibold text-blue-400">{Math.round(renderTask.progress)}%</p>
              </div>
              <div>
                <p className="text-xs text-slate-400 mb-1">Status</p>
                <p className="text-sm font-semibold text-green-400">{renderTask.status}</p>
              </div>
            </div>
          </motion.div>
        )}
      </div>
    </motion.div>
  );
}
