from manim import *
import json
import os
import glob

class DynamicScene(Scene):
    def construct(self):
        # 1. UI Setup
        title = Text("Live Code Execution", font_size=36, weight=BOLD, color=BLUE).to_edge(UP)
        self.add(title)

        # 2. Find the JSON trace file generated by your FastAPI backend
        # Look in multiple possible directories
        list_of_files = glob.glob('media/*_trace.json')
        if not list_of_files:
            list_of_files = glob.glob('../media/*_trace.json')
        if not list_of_files:
            list_of_files = glob.glob('D:/Downloads/project-bolt-sb1-yfxnu6dz/project/backend/media/*_trace.json')
        
        if not list_of_files:
            self.add(Text("Error: No trace data found.", color=RED))
            self.wait(2)
            return
            
        latest_trace_file = max(list_of_files, key=os.path.getctime)
        
        with open(latest_trace_file, 'r') as f:
            trace_data = json.load(f)

        if not trace_data:
            self.add(Text("Execution trace is empty.", color=YELLOW))
            return

        # 3. Reconstruct the code block for the Left Side
        max_line = max(step["line_number"] for step in trace_data if step["line_number"] > 0)
        code_lines = [""] * max_line
        for step in trace_data:
            line_idx = step["line_number"] - 1
            if 0 <= line_idx < len(code_lines):
                 code_lines[line_idx] = step["active_code"]
        
        raw_code = "\n".join(code_lines)

        # 4. Draw the Code Window (Left Side) - Using Text for compatibility
        code_display = Text(raw_code, font="Monospace", font_size=20).to_edge(LEFT, buff=0.5).shift(DOWN * 0.5)
        
        self.play(FadeIn(code_display))

        # 5. Draw the Variables Tracker (Right Side)
        var_title = Text("Memory / Variables", font_size=28, color=YELLOW).to_edge(RIGHT, buff=1.5).shift(UP * 1.5)
        var_text = Text("{}", font_size=24, font="Monospace", color=WHITE).next_to(var_title, DOWN, buff=0.5)
        
        var_box = SurroundingRectangle(var_title, color=WHITE, fill_color=BLACK, fill_opacity=0.8, buff=0.5)
        var_box.stretch_to_fit_height(5)
        var_box.stretch_to_fit_width(5)
        var_box.move_to(var_title.get_center() + DOWN * 2)

        self.play(Create(var_box), FadeIn(var_title), FadeIn(var_text))

        # 6. The Animation Loop (The Magic!)
        for step in trace_data:
            # Format the variables nicely
            vars_state = step.get("variables_state", {})
            var_state_str = json.dumps(vars_state, indent=2)
            new_var_text = Text(var_state_str, font_size=24, font="Monospace", color=GREEN).move_to(var_text.get_center())

            self.play(Transform(var_text, new_var_text), run_time=0.5)
            self.wait(0.5)
            
        self.wait(2)
